### ISSUE TITLE
Consider -4 values in wof:parent_id property

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/py-mapzen-whosonfirst-hierarchy#1]
Similar to how we use the `-3` value in the `wof:parent_id` property, we use a `-4` property to represent multiple "legal" parents (see: [New York City](https://whosonfirst.mapzen.com/spelunker/id/85977539/#9/40.6979/-73.9797)).

The hierarchy library has rules and references `-3` values and should be updated to also handle `-4` values in the `wof:parent_id` property. 

**Occurances:**
- https://github.com/whosonfirst/py-mapzen-whosonfirst-hierarchy/blob/master/mapzen/whosonfirst/hierarchy/__init__.py#L50
- https://github.com/whosonfirst/py-mapzen-whosonfirst-hierarchy/blob/master/mapzen/whosonfirst/hierarchy/__init__.py#L297
- https://github.com/whosonfirst/py-mapzen-whosonfirst-hierarchy/blob/master/mapzen/whosonfirst/hierarchy/__init__.py#435

**Comment by thisisaaronland** [comment]
@stepps00 – The first two cases have been addressed. What is / are the conditions that would flag a parent as `-4` ? For example, a parent ID of `-3` is assigned when:

```
        ambiguous = [ 'neighbourhood', 'microhood', 'campus', 'address', 'building', 'venue' ]
        self.is_ambiguous = ambiguous

        if feature['properties']['wof:placetype'] in self.is_ambiguous:
             feature['properties']['wof:parent_id'] = -3
```

**Comment by stepps00** [comment]
@thisisaaronland - The only difference should be the record's placetype. We discussed a `-4` being assigned whenever there is a legal argument around its parents, which would likely only happen to a placetype of locality or above..

I would expect the parent value to be assigned through something like:

```
        ambiguous_three = [ 'borough', 'macrohood', 'neighbourhood', 'microhood', 'campus', 'address', 'building', 'venue' ]
        self.is_ambiguous = ambiguous_three

        if feature['properties']['wof:placetype'] in self.is_ambiguous:
             feature['properties']['wof:parent_id'] = -3
```
and

```
        ambiguous_four = [ 'locality', 'macroregion', 'region', 'macrocounty', 'county']
        self.is_ambiguous = ambiguous_four

        if feature['properties']['wof:placetype'] in self.is_ambiguous:
             feature['properties']['wof:parent_id'] = -4
```
